version: 2
jobs:
  build:
    working_directory: ~/circleci-gh-pages
    docker:
      - image: circleci/ruby:2.5-node-browsers
    steps:
      - checkout
      - run: bundle install
      - run: "./render_local.rb all"
      - run: sudo apt-get update && sudo apt-get install -y awscli
      - run: cp -r ~/circleci-gh-pages/assets/ ~/circleci-gh-pages/developer
      - run: aws --region eu-west-1 s3 sync ~/circleci-gh-pages/developer/ s3://developer-pages.neo4j.com/developer/ --delete
  publish:
    working_directory: ~/circleci-publish
    docker:
      - image: circleci/ruby:2.5-node-browsers
    steps:
      - checkout
      - run: bundle install
      - run:
          name: "Verify"
          command: "./render.rb all"
          environment:
            ASCIIDOC_TEMPLATES_DIR: "_templates/wordpress"
      - run: sudo apt-get update && sudo apt-get install -y awscli
      - run: aws --region eu-west-1 s3 sync ~/circleci-publish/developer/ s3://developer-pages.neo4j.com/wp/ --delete
      - run:
          name: "Publish"
          command: "./render.rb all"
          environment:
            PUBLISH: true
            BLOG_HOSTNAME: neo4j.com
            BLOG_USERNAME: developer_site
            BLOG_REST_HOSTNAME: https://neo4j.com
            BLOG_REST_USERNAME: restapi
            ASCIIDOC_TEMPLATES_DIR: "_templates/wordpress"

workflows:
  version: 2
  developer-pages:
    jobs:
      - build:
          filters:
            branches:
              only: gh-pages

      - publish:
          filters:
            branches:
              only: publish
